export const PERMISSIONS = {
  // Patients
  PATIENTS_READ: 'patients:read',
  PATIENTS_WRITE: 'patients:write',
  PATIENTS_DELETE: 'patients:delete',

  // Appointments
  APPOINTMENTS_READ: 'appointments:read',
  APPOINTMENTS_WRITE: 'appointments:write',
  APPOINTMENTS_DELETE: 'appointments:delete',

  // Procedures
  PROCEDURES_READ: 'procedures:read',
  PROCEDURES_WRITE: 'procedures:write',
  PROCEDURES_DELETE: 'procedures:delete',

  // Staff
  STAFF_READ: 'staff:read',
  STAFF_WRITE: 'staff:write',
  STAFF_DELETE: 'staff:delete',

  // Statistics
  STATISTICS_READ: 'statistics:read',

  // Administration
  ADMIN_READ: 'admin:read',
  ADMIN_WRITE: 'admin:write',
  ADMIN_DELETE: 'admin:delete',

  // System
  SYSTEM_ADMIN: 'system:admin',
};

export const ROLES = {
  ADMIN: 'admin',
  DOCTOR: 'doctor',
  NURSE: 'nurse',
  RECEPTIONIST: 'receptionist',
};

export const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: [
    PERMISSIONS.PATIENTS_READ,
    PERMISSIONS.PATIENTS_WRITE,
    PERMISSIONS.PATIENTS_DELETE,
    PERMISSIONS.APPOINTMENTS_READ,
    PERMISSIONS.APPOINTMENTS_WRITE,
    PERMISSIONS.APPOINTMENTS_DELETE,
    PERMISSIONS.PROCEDURES_READ,
    PERMISSIONS.PROCEDURES_WRITE,
    PERMISSIONS.PROCEDURES_DELETE,
    PERMISSIONS.STAFF_READ,
    PERMISSIONS.STAFF_WRITE,
    PERMISSIONS.STAFF_DELETE,
    PERMISSIONS.STATISTICS_READ,
    PERMISSIONS.ADMIN_READ,
    PERMISSIONS.ADMIN_WRITE,
    PERMISSIONS.ADMIN_DELETE,
    PERMISSIONS.SYSTEM_ADMIN,
  ],

  [ROLES.DOCTOR]: [
    PERMISSIONS.PATIENTS_READ,
    PERMISSIONS.PATIENTS_WRITE,
    PERMISSIONS.APPOINTMENTS_READ,
    PERMISSIONS.APPOINTMENTS_WRITE,
    PERMISSIONS.PROCEDURES_READ,
    PERMISSIONS.PROCEDURES_WRITE,
    PERMISSIONS.STATISTICS_READ,
  ],

  [ROLES.NURSE]: [
    PERMISSIONS.PATIENTS_READ,
    PERMISSIONS.APPOINTMENTS_READ,
    PERMISSIONS.PROCEDURES_READ,
    PERMISSIONS.PROCEDURES_WRITE,
  ],

  [ROLES.RECEPTIONIST]: [
    PERMISSIONS.PATIENTS_READ,
    PERMISSIONS.PATIENTS_WRITE,
    PERMISSIONS.APPOINTMENTS_READ,
    PERMISSIONS.APPOINTMENTS_WRITE,
  ],
};

export default { PERMISSIONS, ROLES, ROLE_PERMISSIONS };